### ISSUE TITLE
spinner gets stuck while opening a post

### ISSUE THREAD

**Issue by dominictarr** [ssbc/patchwork-ui#406]
running the latest code, it updated quickly (pretty much as soon as i opened it) but then following a link to the message just starts the spinner, which seems to get stuck. 

this message:  %JHEU0XnVoMXxp2bCgenX7r10OJdfDbppdGHkLzbj0/k=.sha256

I was still able to communicate with sbot via the cli, so it seems this is something in patchwork.

The spinner blocks the whole UI (including nav buttons)!

**Comment by pfraze** [comment]
That's always a sign of an unhandled exception during the page-transition -- the spinner comes on because the page-load is "taking a long time." This issue has two parts:

 1. A control-stealing loader doesn't make sense for page transitions. It was created for tasks that the users shouldn't try to interrupt, and page-transitions are not one of those.
 2. Unhandled exceptions should bubble up to the user.

**Comment by dominictarr** [comment]
i saw some errors in the console.
```
[13991:0811/172356:INFO:CONSOLE(130)] "TypeError: src.replace is not a function
Please report this to https://github.com/chjj/marked.", source: /home/dominic/c/ssb/patchwork/node_modules/ssb-patchwork-ui/lib/com/message-content.js (130)
[13991:0811/172356:INFO:CONSOLE(257)] "Uncaught ReferenceError: thread is not defined", source: /home/dominic/c/ssb/patchwork/node_modules/ssb-patchwork-ui/lib/com/message.js (257)
```

Is there a way we can catch these errors and present something to the user? spinning forever is pretty much the worst thing we can do here

**Comment by pfraze** [comment]
Yeah, that's my number 2 item there.

**Comment by pfraze** [comment]
Ok, I have committed a much nicer error modal (includes stack and an automatic github-issue reporter tool!) and have removed the spinner from page transitions.

**Comment by dominictarr** [comment]
awesome!

**Comment by dominictarr** [comment]
I can't switch to any other views. I get this error on startup:

```
ReferenceError: thread is not defined
    at renderSignals (/home/dominic/c/ssb/patchwork-ui/lib/com/message.js:287:58)
    at /home/dominic/c/ssb/patchwork-ui/lib/com/message.js:169:7
    at /home/dominic/c/ssb/patchwork-ui/node_modules/multicb/index.js:14:16
    at Object.exports.decryptThread (/home/dominic/c/ssb/patchwork-ui/lib/util.js:265:3)
    at /home/dominic/c/ssb/patchwork-ui/lib/com/message.js:166:7
    at Object._requests.(anonymous function) (/home/dominic/c/ssb/patchwork-ui/node_modules/muxrpc/node_modules/packet-stream/index.js:37:5)
    at PacketStream._onrequest (/home/dominic/c/ssb/patchwork-ui/node_modules/muxrpc/node_modules/packet-stream/index.js:139:26)
    at PacketStream.write (/home/dominic/c/ssb/patchwork-ui/node_modules/muxrpc/node_modules/packet-stream/index.js:122:41)
    at /home/dominic/c/ssb/patchwork-ui/node_modules/muxrpc/pull-weird.js:52:15
    at /home/dominic/c/ssb/patchwork-ui/node_modules/muxrpc/node_modules/pull-stream/sinks.js:15:33
```
when I try and click on other views, nothing happens.

**Comment by pfraze** [comment]
https://github.com/ssbc/ssb-msg-schemas/pull/11 is not merged

**Comment by pfraze** [comment]
oh nm, seeing your pr now
